stages:
  - name: coffea-plot
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        coffea_plot: '{workdir}/PF_n.png'
      step: {$ref: workflow/steps.yaml#/coffea-plot}
  - name: rdf-plot
    scheduler:
      scheduler_type: singlestep-stage
      parameters:
        rdf_plot: '{workdir}/nPFCands.png'
      step: {$ref: workflow/steps.yaml#/rdf-plot}
